DEPENDS=thesis.tex abstract.tex introduction.tex related.tex method.tex results.tex results2.tex thesis.bib thesis.bst thesis.cls umthstd.clo umthcfm.clo umth10pt.clo umth11pt.clo umth12pt.clo 

.PHONY: all
all: thesis.pdf

include ~/Code/latex.mk


